#' Check if an AVL dataframe meets TIDES standards.
#'
#' @description
#' The transit integrated data exchange standard (TIDES) specifies columns that
#' should be present in AVL data tables and the data types of these columns.
#' This function verifies if those columns are present in the input `avl_df`,
#' and those columns are of the correct data type. See `Details` for
#' more information.
#'
#' @details
#' The AVL cleaning functions in this package generally require the input
#' dataframes to adhere to the TIDES `vehicle_locations`
#' [table schema](https://tides-transit.org/main/tables/#vehicle-locations). The
#' following columns and data types are checked by this validator:
#'
#' - `location_ping_id`: Should be a `character` string.
#'
#' - `trip_id_performed`: Should be a `character` string.
#'
#' - `event_timestamp`: Should be a `POSIXct` date-time.
#'
#' - `vehicle_id`: Should be a `character` string.
#'
#' - `operator_id`: Should be a `character` string. This field is not standard
#' in TIDES `vehicle_locations`, and is not a strict requirement for any AVL
#' processing functions.
#'
#' - `longitude` and `latitude`: Should be `numeric`. These fields are required
#' only to linearize AVL data, and not used afterwards.
#'
#' - `distance`: Should be `numeric`. This field is not standard in TIDES
#' `vehicle_locations`, and is generated by `get_linear_distances()`. It is
#' required by most other AVL processing functions.
#'
#' - `speed`: Should be `numeric`. This field is not a strict requirement for
#' any AVL processing functions.
#'
#' Each AVL processing function in `transittraj` uses specific fields. Each
#' function verifies that the required fields and data types are present before
#' proceeding.
#'
#' @param avl_df A dataframe of AVL data, either in GPS (longitude/latitude)
#' form or linearized distance form.
#' @return A dataframe of each required field, required data type, whether
#' the field is present, and whether the data type matches expectations.
#' @export
validate_tides <- function(avl_df) {
  # Set required columns & datatypes
  required_columns <- c("location_ping_id",
                        "trip_id_performed",
                        "event_timestamp",
                        "vehicle_id",
                        "operator_id",
                        "longitude", "latitude",
                        "distance",
                        "speed")
  required_data_types <- c("character",
                           "character",
                           "POSIXct",
                           "character",
                           "character",
                           "numeric", "numeric",
                           "numeric",
                           "numeric")

  # Get if each column is present in DF
  cols_present_bool <- required_columns %in% names(avl_df)

  # Get if datatypes match
  cols_types <- c(class(avl_df$location_ping_id)[1],
                  class(avl_df$trip_id_performed)[1],
                  class(avl_df$event_timestamp)[1],
                  class(avl_df$vehicle_id)[1],
                  class(avl_df$operator_id)[1],
                  class(avl_df$longitude)[1], class(avl_df$latitude)[1],
                  class(avl_df$distance)[1],
                  class(avl_df$speed)[1])
  cols_types_bool <- cols_types == required_data_types

  # Compile results into DF
  validation_results <- data.frame(required_field = required_columns,
                                   required_field_type = required_data_types,
                                   field_present = cols_present_bool,
                                   actual_field_type = cols_types,
                                   field_type_ok = cols_types_bool) %>%
    dplyr::mutate(field_ok = (field_type_ok & field_present))
  return(validation_results)
}

#' Uses `validate_tides` and an input vector of needed fields to check whether
#' an AVL DF meets the requirements of a given function.
#'
#' Intended for internal use only.
validate_input_to_tides <- function(needed_fields, avl_df) {

  # Get validation -- filter & sort
  avl_val <- validate_tides(avl_df) %>%
    dplyr::filter(required_field %in% needed_fields) %>%
    dplyr::arrange(match(required_field, needed_fields))

  # Check presence of fields
  if (!all(avl_val$field_present)) {
    stop(paste("Missing required fields:",
               avl_val$required_field[!avl_val$field_present]))
  }

  # Check data types of fields
  if (!all(avl_val$field_type_ok)) {
    stop(paste("The following fields do not have the correct data type:",
               avl_val$required_field[!avl_val$field_type_ok]))
  }
}
